name: flutter_tasktracker
description: A Flutter front-end for the Flask Household Task Tracker

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.20.2
  url_launcher: ^6.1.9
  flutter_local_notifications: ^18.0.1
  fl_chart: ^0.70.2
  firebase_core: ^3.10.1   # Use latest if available
  firebase_messaging: ^15.2.1   # Use latest if available
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/molen.png
